export const similarMoviesTypes = {
	SEARCH_SIMILAR_MOVIES_REQUEST:
		"[similar movies] SEARCH_SIMILAR_MOVIES_REQUEST",
	SEARCH_SIMILAR_MOVIES_SUCCESS:
		"[similar movies] SEARCH_SIMILAR_MOVIES_SUCCESS",
	SEARCH_SIMILAR_MOVIES_FAILURE:
		"[similar movies] SEARCH_SIMILAR_MOVIES_FAILURE",
	SEARCH_SIMILAR_TVSHOWS_REQUEST: "[similar tv] SEARCH_SIMILAR_TVSHOWS_REQUEST",
	SEARCH_SIMILAR_TVSHOWS_SUCCESS: "[similar tv] SEARCH_SIMILAR_TVSHOWS_SUCCESS",
	SEARCH_SIMILAR_TVSHOWS_FAILURE: "[similar tv] SEARCH_SIMILAR_TVSHOWS_FAILURE"
};
