export const similarMoviesTypes = {
	SEARCH_SIMILAR_MOVIES_REQUEST:
		"[similar movies] SEARCH_SIMILAR_MOVIES_REQUEST",
	SEARCH_SIMILAR_MOVIES_SUCCESS:
		"[similar movies] SEARCH_SIMILAR_MOVIES_SUCCESS",
	SEARCH_SIMILAR_MOVIES_FAILURE:
		"[similar movies] SEARCH_SIMILAR_MOVIES_FAILURE"
};
