export const userTypes = {
	USER_LOGIN_SUCCESS: "[user] USER_LOGIN_SUCCESS",
	USER_LOGIN_FAILURE: "[user] USER_LOGIN_FAILURE",
	USER_LOGOUT: "[user] USER_LOGOUT",
	USER_LOADED: "[user] USER_LOADED",
	USER_LOADING: "[user] USER_LOADING",
	USER_REGISTER_SUCCESS: "[user] USER_REGISTER_SUCCESS",
	USER_REGISTER_FAILURE: "[user] USER_REGISTER_FAILURE",
	AUTH_ERROR: "[auth] AUTH_ERROR"
};
